version: '3.3'

services:
  DB:
    image: meeting_db
    restart: unless-stopped
    env_file:
      - db.env
    expose:
      - "5432"
    ports:
      - 5435:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  REDIS:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - 6379
  MIGRATION_DEV:
    image: meeting_backend
    working_dir: /opt/app/backend
    command: >
      sh -c "yarn
             yarn run mi:run"
    volumes:
      - ./app:/opt/app
    env_file:
      - backend_dev.env
    depends_on:
      - DB
  INSTALL_BACK:
    image: meeting_backend
    working_dir: /opt/app/backend
    command: >
      sh -c "yarn"
    volumes:
      - ./app:/opt/app
    env_file:
      - backend_dev.env
  INSTALL_FRONT:
    image: meeting_frontend
    working_dir: /opt/app/frontend
    command: >
      sh -c "yarn"
    volumes:
      - ./app:/opt/app
    env_file:
      - frontend_dev.env
  EMPTY_BACK:
    image: meeting_backend
    working_dir: /opt/app/backend
    volumes:
      - ./app:/opt/app
    env_file:
      - backend_dev.env
  EMPTY_FRONT:
    image: meeting_frontend
    working_dir: /opt/app/frontend
    volumes:
      - ./app:/opt/app
    env_file:
      - frontend_dev.env
  SERVER_DEV:
    image: meeting_backend
    restart: unless-stopped
    working_dir: /opt/app/backend
    command: >
      sh -c "yarn run start:dev"
    volumes:
      - ./app:/opt/app
    env_file:
      - backend_dev.env
    expose:
      - "3000"
    ports:
      - 0.0.0.0:3000:3000
    depends_on:
      - DB
      - REDIS
  FRONTEND_DEV:
    image: meeting_frontend
    restart: unless-stopped
    working_dir: /opt/app/frontend
    command: >
      sh -c "yarn run start"
    volumes:
      - ./app:/opt/app
    env_file:
      - frontend_dev.env
    ports:
      - 0.0.0.0:8080:8080
    depends_on:
      - SERVER_DEV
